### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by palfrey** [twisted/axiom#106]
Is there any interest in Python 3 support? If I submitted patches that added Python 3 support (while still keeping 2.x) would that be something that could plausibly get merged?

**Comment by mithrandi** [comment]
I definitely think we can merge those (following the usual review process)! Unfortunately the review process may take a while as most (all?) of the Axiom contributors don't have that much time to spend on the project these days, but hopefully we can manage. I would definitely advise submitting smaller individual patches rather than one big monster patch.

**Comment by ldanielburr** [comment]
Agreed, small patches make the task of review much less daunting when the reviewer's time is limited.  I think it would be great if you put up some PRs to move Axiom towards Python 3 compatibility :)

**Comment by glyph** [comment]
@palfrey Yes! Submitting a couple of PRs to start porting modules over to py3 compatible syntax would be much appreciated.

**Comment by palfrey** [comment]
So I had a quick look at this the other day, and the first problem is patches for Epsilon to get it to Python 3, as without that we can't upgrade this. I'll have a look at that first.

**Comment by ldanielburr** [comment]
@palfrey, please note https://github.com/twisted/epsilon/pull/33, which might give you a jump-start on porting Epsilon.
