### ISSUE TITLE
Question: raw queries?

### ISSUE THREAD

**Issue by lfdversluis** [twisted/axiom#73]
To gain some performance in a project we want to do database IO on separate threads asynchronously. The project already heavily includes Twisted so Axiom may be a good fit (we are also thinking about Storm as it has Twisted support somewhat).
Currently, all the the queries are plain sql queries (raw). We would like to move towards an ORM approach, but gradually.
Does axiom have functionalities to run normal sql queries asynchronously? Or any documentation on this? We currently use a sqlite3 database if it matters.

**Comment by mithrandi** [comment]
As far as executing raw queries goes, there are a few public methods on `Store` for this: primarily `Store.querySQL` and `Store.executeSQL`.

As far as asynchronous queries go, Axiom is explicitly designed for synchronous use, and all of the low-level APIs are synchronous (there are some higher level things like `axiom.batch` that are asynchronous, however). Axiom stores are also explicitly not threadsafe (you must only use the `Store` in the same thread you created it), and opening the same database concurrently (eg. by creating one `Store` per thread, or opening the database in multiple processes) is likely to lead to consistency issues (due to how the item cache works).

In addition, trying to use Axiom on top of an existing database schema may be awkward, since Axiom expects to "own" the schema, and keeps a bunch of metadata relating to items (rows) and types (tables) already in the database.

It sounds like your needs may best be addressed by using an ORM-ish layer that is less opinionated than Axiom.
